CREATE TABLE `inchise` (
	`id` int AUTO_INCREMENT NOT NULL,
	`client` text,
	`produs` text,
	`judet` text,
	`localitate` text,
	`feedback` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `inchise_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `service` (
	`id` int AUTO_INCREMENT NOT NULL,
	`caz_numarul` text,
	`client` text,
	`comanda_de_lucru` text,
	`raspunsuri_comenzi` text,
	`produs` text,
	`serie` text,
	`problema` text,
	`data_sesizare` text,
	`data_receptie` text,
	`solutionare` text,
	`motiv_garantie` text,
	`data_iesire` text,
	`finalizat` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `service_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `servicii` (
	`id` int AUTO_INCREMENT NOT NULL,
	`produs` text,
	`data_control` text,
	`vanzator` text,
	`status` text,
	`cumparator` text,
	`raspunsuri` text,
	`comenzi_de_lucru` text,
	`valoare` text,
	`plata` text,
	`rata2` text,
	`rata3` text,
	`rata4` text,
	`bonus` text,
	`servicii_suplimentare` text,
	`livrare_cf_contract` text,
	`data_montaj` text,
	`pif_cf_contract` text,
	`judet` text,
	`localitate` text,
	`detalii` text,
	`mentiuni` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `servicii_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `stoc_real` (
	`id` int AUTO_INCREMENT NOT NULL,
	`produs` text,
	`de_comandat` text,
	`disponibil_vanzare` text,
	`vanzator` text,
	`status` text,
	`cumparator` text,
	`raspunsuri_vanzatori` text,
	`comenzi_de_lucru` text,
	`valoare_contract` text,
	`plata` text,
	`rata2` text,
	`rata3` text,
	`bonus` text,
	`servicii_suplimentare` text,
	`rata2_livrare_structura` text,
	`data_approx_livrare` text,
	`rata_finala_pif` text,
	`judet` text,
	`localitate` text,
	`detalii` text,
	`index_nr` text,
	`comentarii_operational` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `stoc_real_id` PRIMARY KEY(`id`)
);
